---
title: "Perception and action project"
author: "Lina Walkowiak and Amélie Kretschmer"
date: "2023-12-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r install_packages}

pacman::p_load(devtools, tidyverse, dplyr, ggplot2, jsonlite, tidyr, car, rstatix, lme4, fitdistrplus, extraDistr, brms, stats, ggpubr, rstatix, boot, dunn.test)
library(pupilr)
library(eyer)

```

```{r read_info_data}
infos <- read_csv("/Users/lina/Documents/3rd_semester/Perception_and_Action/raw_data/sections.csv")
answers <- read_csv("/Users/lina/Documents/3rd_semester/Perception_and_Action/exam_project/answers.csv")
# Assuming df1 and df2 are your two data frames, and "id" is the common identifier
infos <- merge(infos, answers, by = "id", all.x = TRUE)

# remove unneeded columns from infos df
infos <- infos[, -c(2, 5,6,7,8,9,10,13,21)]

# rename for merging 
colnames(infos) <- gsub(" ", ".", colnames(infos))
```
```{r compute_statistics}
mean(answers$age)
range(answers$age)

```


```{r specify_paths}
main_folder <- "/Users/lina/Documents/3rd_semester/Perception_and_Action/raw_data/"
subfolders <- list.dirs("/Users/lina/Documents/3rd_semester/Perception_and_Action/raw_data/", full.names = T, recursive = T)
```



```{r read_fixations, message = F}

# create list of "fixations.csv" paths
fixations <- lapply(subfolders, function(subfolder) {
  # file path within each subfolder
  fixations_path <- file.path(subfolder, "fixations.csv")

  # Check if the file exists
  if (file.exists(fixations_path)) {
    # if the file exists, return the file path
    return(fixations_path)
  } else {
    # if the file does not exist, return NULL
    return(NULL)
  }
})

# Remove NULL Values from the list 
fixations <- Filter(Negate(is.null), fixations)

# Read and Combine CSV filess
fixations <- bind_rows(lapply(fixations, read.csv))

# remove unwanted columns 
fixations <- fixations[, - c(1, 7, 8, 9, 10)]

fixations <- rename(fixations, start = start.timestamp..ns., end = end.timestamp..ns.,
                    duration = duration..ms.)


fixations$start <- fixations$start / 1e6
fixations$end <- fixations$end / 1e6


```



```{r read_gaze, message=F}
# create list of paths
# gaze <- lapply(subfolders, function(subfolder) {
#   # file path within each subfolder
#   gaze_path <- file.path(subfolder, "gaze.csv")
# 
#   # Check if the file exists
#   if (file.exists(gaze_path)) {
#     # if the file exists, return the file path
#     return(gaze_path)
#   } else {
#     # if the file does not exist, return NULL
#     return(NULL)
#   }
# })
# 
# # Remove NULL values from the list 
# gaze <- Filter(Negate(is.null), gaze)
# 
# # Read and combine CSV files 
# gaze <- bind_rows(lapply(gaze, read.csv))

# if we use the data maybe rename xolumsn and so on

```


```{r read_events}
# create list of events paths
events <- lapply(subfolders, function(subfolder) {
  # file path within each subfolder
  events_path <- file.path(subfolder, "events.csv")

  # check if the file exists
  if (file.exists(events_path)) {
    # if the file exists, return the file path
    return(events_path)
  } else {
    # if the file does not exist, return NULL
    return(NULL)
  }
})

# remove NULL values from the list 
events <- Filter(Negate(is.null), events)

# combine 
events <- bind_rows(lapply(events, read.csv))

events <- rename(events, task.time = timestamp..ns.)

events$task.time <- events$task.time /1e6



```

```{r task_time}
events <- subset(events, type == "cloud")

# create begin and end columns with time stamp
events <- events %>%
  group_by(recording.id, name) %>%
  summarise(task_time = first(task.time), .groups = "drop") %>%
  pivot_wider(
    id_cols = recording.id,
    names_from = name,
    values_from = task_time
  ) %>%
  rename(
    task.begin = "task.begin",
    task.end = "task.end"
  )
```


```{r bind_and_filter}
# bind events and fixation data
fixations <- left_join(events, fixations, by = "recording.id")

# filter fixation events that are within the task duration 
fixations <- fixations  %>%
  filter(start > task.begin, end < task.end)


```

```{r merge_data}

info_fix <- left_join(fixations, infos, by="recording.id")

```

```{r add_metrics}

info_fix$task.duration <- info_fix$task.end - info_fix$task.begin
info_fix <- info_fix %>%
  group_by(recording.id) %>%
  mutate(
    fixation.freq = n_distinct(fixation.id) / task.duration)
```


```{r plot_for_fun}

my_palette <- c("#66c2a5", "#fc8d62", "#8da0cb", "#e78ac3")

# fixation duration boxplot
info_fix %>%
  ggplot(aes(x = condition, y = duration , fill = condition)) +
  geom_boxplot() +
  labs(title = "Fixation Duration in Each Condition",
       x = "Condition",
       y = "Fixation Duration")+ 
      scale_fill_manual(values=my_palette)+
      theme_bw()

# overalll fixation duration 
info_fix %>%
  ggplot(aes(x = duration)) +
  geom_density(alpha = 0.5, fill = "#66c2a5") +
  labs(title = "Fixation Duration Distribution",
       x = "Fixation Duration",
       y = "Density") +
  theme_bw() 

#fixation duration density wrapped by condiotn 
info_fix %>%
  ggplot(aes(x = duration, fill = condition)) +
  geom_density(alpha = 0.5) +
  labs(title = "Fixation Duration Distribution",
       x = "Fixation Duration",
       y = "Density") +
  scale_fill_manual(values = my_palette) +
  theme_bw() +
  facet_wrap(~condition, scale = "fixed")



# overall fixation frequency
info_fix %>%
  ggplot(aes(x = fixation.freq)) +
  geom_density(alpha = 0.8, fill = "#fc8d62") +
  labs(title = "Fixation Frequency Distribution",
       x = "Fixation Frequency",
       y = "Density") +
  theme_bw()


# fixation frequency 
info_fix %>%
  ggplot(aes(x = fixation.freq, fill = condition)) +
  geom_density(alpha = 0.5) +
  labs(title = "Fixation Frequency Distribution",
       x = "Fixation Frequency",
       y = "Density") +
  scale_fill_manual(values = my_palette) +
  theme_bw() +
  facet_wrap(~condition, scale = "fixed")
# showing the fixations per second 


# boxplot fixation frequency 
info_fix %>%
  ggplot(aes(x = condition, y = fixation.freq , fill = condition)) +
  geom_boxplot() +
  labs(title = "Fixation Frequency in Each Condition",
       x = "Condition",
       y = "Fixation Frequency")+ 
      scale_fill_manual(values=my_palette)+
      theme_bw()

# mean fixation duration in one session grouped by condition
info_fix %>%
  group_by(recording.id, condition) %>%
  summarise(mean_duration = mean(duration)) %>%
  ggplot(aes(x = mean_duration, fill = condition)) +
  geom_density(alpha = 0.5) +
  labs(title = "Mean Fixation Duration Distribution",
       x = "Mean Fixation Duration",
       y = "Density") +
  scale_fill_manual(values = my_palette) +
  theme_bw()+ 
    facet_wrap(~condition, scale = "fixed")

```


```{r classes_df}
# Create the fix_classes data frame
fix_classes <- info_fix %>%
  group_by(recording.id) %>%
  summarise(
    ambient = sum(duration <= 300),
    focal = sum(duration > 300),
    fix_count = focal + ambient,
    condition = first(condition),
    episode = first(episode),
    id = first(id)
  )

# Calculate the proportion of focla to ambient fixations
fix_classes <- fix_classes %>%
  mutate(prop_focal_to_ambient =  focal / ambient)

```

```{r merge_classes_and_plot}
fix_classes <- fix_classes[, c("recording.id", "prop_focal_to_ambient")]
id_rec_id <- info_fix[, c("id", "recording.id", "condition")]
fix_classes <- left_join(fix_classes, id_rec_id, by= "recording.id" )
fix_classes <- fix_classes[!duplicated(fix_classes, fromLast = TRUE), ]


ggplot(fix_classes, aes(x = condition, y = prop_focal_to_ambient, fill = condition)) +
  geom_boxplot() +
  labs(x = "ID", y = "Proportion (prop_focal_to_ambient)", title = "Proportion of Focal to Ambient Fixations Across Conditions") +
  theme_minimal()+
  scale_fill_manual(values = my_palette)

fix_classes %>%
  ggplot(aes(x = prop_focal_to_ambient, fill = condition)) +
  geom_density(alpha = 0.5) +
  labs(title = "Proportion of Focal to Ambient Fixations Across Conditions",
       x = "Proportion",
       y = "Density") +
  scale_fill_manual(values = my_palette) +
  theme_bw() +
  facet_wrap(~condition, scale = "fixed")

fix_classes %>%
  ggplot(aes(x = log(prop_focal_to_ambient), fill = condition)) +
  geom_density(alpha = 0.5) +
  labs(title = "Log (Proportion of Focal to Ambient Fixations Across Conditions)",
       x = "Proportion",
       y = "Density") +
  scale_fill_manual(values = my_palette) +
  theme_bw() +
  facet_wrap(~condition, scale = "fixed")
```


```{r time_between_fixations}
# calculate the time between fixation = saccades ???

fixations <- fixations %>%
  group_by(recording.id) %>%
  mutate(time_between_fixations = start - lag(end))
info_fix <- info_fix %>%
  group_by(recording.id) %>%
  mutate(time_between_fixations = start - lag(end))

ggplot(info_fix, aes(x = condition, y = time_between_fixations, fill=condition)) +
  geom_boxplot() +
  labs(title = "Time Between Fixations by Condition",
       x = "Condition",
       y = "Time Between Fixations") +
  theme_bw()+
  scale_fill_manual(values = my_palette)

```
## checking assumptions needed for anova 

```{r filter_data}
lower_threshold <- 50 # change based on literature 
upper_threshold <- 2000 # change based on litertaure 


# Remove outliers
info_fix_filtered <- info_fix[info_fix$duration >= lower_threshold & info_fix$duration <= upper_threshold, ]
```


```{r log_transform_plot}
# Assuming 'info_fix' is your data frame
info_fix_filtered$log_duration <- log(info_fix_filtered$duration)
#fixation duration density wrapped by condiotn 
info_fix_filtered %>%
  ggplot(aes(x = log_duration, fill = condition)) +
  geom_density(alpha = 0.5) +
  labs(title = " Log-transformed Fixation Duration Distribution",
       x = "Log (Fixation Duration)",
       y = "Density") +
  scale_fill_manual(values = my_palette) +
  theme_bw() +
  facet_wrap(~condition, scale = "fixed")



```

```{r norm_test}
qqnorm(info_fix_filtered$log_duration, main = "Normal Q-Q plot")
ggqqplot(info_fix_filtered, "log_duration", facet.by = "condition")
shapiro_test(info_fix_filtered$log_duration)
# does not look good :((((

```
## Modelling fixation duration 

```{r glm_model}
# note this is done with all fixation data, possibly use the filtered df instead

# with logit link 
log_model <- glm(duration ~ condition + (1 | id), data = info_fix, family = poisson(link = "log"))
summary(log_model)  

# or this without log ? 
mixed_model <- lmer(duration ~ condition + (1 | id), data = info_fix)
summary(mixed_model)  # assumes normality otherwise we could use log(duration)

gamma_model <- glm(duration ~ condition + (1 | id), data = info_fix, family = Gamma(link = "log"))
summary(gamma_model)

gamma_model_log <- glm(log_duration ~ condition + (1 | id), data = info_fix, family = Gamma(link = "log"))
summary(gamma_model_log)


```

```{r AIC}
AIC(log_model, mixed_model, gamma_model, gamma_model_log)
```


```{r plot_model}
# Plot model 
plot(gamma_model_log)

```


## Anova on proportion of focal to ambient fixations 

```{r test_proportion}
shapiro.test(log(fix_classes$prop_focal_to_ambient))
# wuhu normally distributed

anova_result <- aov(log(prop_focal_to_ambient) ~ condition, data = fix_classes)
summary(anova_result)

# post-hoc pair-wise group comparison
## here we should probably read up on other options, not sure TurkeyHSD is the best 
TukeyHSD(anova_result)


leveneTest(prop_focal_to_ambient ~ condition, data = fix_classes)
# unequal variance, so we probably need to do something else




## apparently this is suitable if unqueal variances are present
kruskal_result <- kruskal.test(prop_focal_to_ambient ~ condition, data = fix_classes)
print(kruskal_result)# Kruskal-Wallis test

#  post hoc pairwise comparisons (adjusting for multiple comparisons)
posthoc_dunn <- dunn.test(fix_classes$prop_focal_to_ambient, g = fix_classes$condition, method = "bonferroni")
print(posthoc_dunn)

```



